### ISSUE TITLE
pose_gt.txt

### ISSUE THREAD

**Issue by PengSO** [ssmem/vdo-slam-data-preprocess#3]
would you mind telling me how to generate pose_gt.txt ? I'm looking forward to your early reply, thank you!

**Comment by ssmem** [comment]
I think it will be found at odometry and raw_data of kitti.

**Comment by PengSO** [comment]
Thanks for your  reply,  I have sovled  this problem, the author of VDO-SLAM said  the pose_gt.txt  could be found in file/ folder oxts of kitti raw data.



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年05月13日 17:37 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [ssmem/vdo-slam-data-preprocess] pose_gt.txt (Issue #3) |

I think it will be found at odometry and raw_data of kitti.
